environment:
  # Lets get some usefull backtraces on miscompiles
  RUST_BACKTRACE: 1
  
  # The appveyor image we use has a pretty huge set of things installed... we make the
  # initial PATH something sane so we know what to expect
  PATH: "C:\\windows\\system32;\
    C:\\windows;\
    C:\\windows\\System32\\Wbem;\
    C:\\windows\\System32\\WindowsPowerShell\\v1.0;\
    C:\\ProgramData\\chocolatey\\bin;\
    C:\\MinGW\\bin;\
    C:\\Python27;\
    C:\\Python27\\Scripts;\
    C:\\Tools\\PsTools;\
    C:\\Tools\\NuGet3;\
    C:\\Program Files\\Microsoft\\Web Platform Installer\\;\
    C:\\Program Files\\7-Zip;\
    C:\\Program Files\\Mercurial;\
    C:\\Program Files (x86)\\Subversion\\bin;\
    C:\\Program Files (x86)\\CMake\\bin;\
    C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;\
    C:\\Program Files (x86)\\MSBuild\\14.0\\Bin;\
    C:\\Program Files\\Amazon\\AWSCLI\\;\
    C:\\Program Files\\Microsoft Windows Performance Toolkit\\;\
    C:\\Program Files\\LLVM\\bin;\
    C:\\Program Files\\Git LFS;\
    C:\\Program Files\\Git\\cmd;\
    C:\\Program Files\\Git\\usr\\bin;\
    C:\\Program Files\\AppVeyor\\BuildAgent;\
    C:\\Users\\appveyor\\.cargo\\bin;"

  matrix:
    - TARGET: stable-x86_64-pc-windows-msvc
    - TARGET: stable-x86_64-pc-windows-gnu
    - TARGET: stable-i686-pc-windows-msvc
    - TARGET: stable-i686-pc-pc-windows-gnu
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-x86_64-pc-windows-gnu
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: nightly-i686-pc-pc-windows-gnu

# Set cache, so qe can be fast and efficient
cache:
  - C:\Users\appveyor\.rustup
  # Cargo seems to be dumb and ignore the cache, probably doesn't like different timestamps from the restored cache
  # - C:\Users\appveyor\.cargo

# Install and configure 
install:
  # Update git submodules
  - git submodule update --init --recursive

  # Install rustup, Should use i686-pc-windows-gnu triple for first install
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init.exe --verbose -y

  #Set toolchain for current target
  - rustup override set %TARGET%
  
  # Get latest toolchains
  - rustup update
  
  # Show current version
  - rustc -V
  - cargo -V

build_script: 
  - cargo test --all --verbose
  - cargo build --all --verbose

test: off