[package]
name = "imgui-examples"
version = "0.0.22-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "imgui crate examples"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
publish = false

[dev-dependencies]
gfx = "0.17"
gfx_window_glutin = "0.26"
glutin = "0.18"
imgui = { version = "0.0.22-pre", path = "../imgui" }
imgui-gfx-renderer = { version = "0.0.22-pre", path = "../imgui/imgui-gfx-renderer" }
imgui-glutin-support = { version = "0.0.22-pre", path = "../imgui/imgui-glutin-support" }
