[package]
name = "imgui-sys"
version = "0.0.16-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>", "imgui-rs contributors"]
description = "Raw FFI bindings to dear imgui"
homepage = "https://github.com/Gekkio/imgui-rs"
repository = "https://github.com/Gekkio/imgui-rs"
license = "MIT/Apache-2.0"
categories = ["gui", "external-ffi-bindings"]
build = "build.rs"

[badges]
travis-ci = { repository = "Gekkio/imgui-rs" }

[dependencies]
bitflags = "0.9"
glium = { version = "0.17", default-features = false, optional = true }
gfx = { git = "https://github.com/gfx-rs/gfx.git", optional = true }

[build-dependencies]
cc = "1.0"
